[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "slmsuite"
readme = "README_PYPI.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["version", "dependencies", "description", "authors"]

[project.urls]
Homepage = "https://slmsuite.readthedocs.io/en/latest/"
Repository = "https://github.com/slmsuite/slmsuite"
Documentation = "https://slmsuite.readthedocs.io/en/latest/"
Issues = "https://github.com/slmsuite/slmsuite/issues"

[tool.poetry]
name = "slmsuite"
version = "0.2.0"
description = "Package for high-performance spatial light modulator (SLM) control and holography."
license = "MIT"
authors = ["slmsuite developers <qp-slm@mit.edu>"]
readme = "README.md"
homepage = "https://slmsuite.readthedocs.io/en/latest/"
repository = "https://github.com/slmsuite/slmsuite"
documentation = "https://slmsuite.readthedocs.io/en/latest/"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python =            "^3.9"
numpy =             ">=1.21.6"
scipy =             "^1.6.1"
opencv-python =     "^4.6.0"
matplotlib =        "^3.5.3"
h5py =              "^3.7.0"
tqdm =              "^4.60.0"

jupyter =           { version="^1.0.0", optional=true }

imageio =           { version="^2.9.0", optional=true }
imageio-ffmpeg =    { version="^0.4.8", optional=true }
pygifsicle =        { version="^1.1.0", optional=true }

line-profiler =     { version="^4.1.3", optional=true }
snakeviz =          { version="^2.2.2", optional=true }

[tool.poetry.extras]
ipython = ["jupyter"]